apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-webpage
  labels:
   app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
       app: nginx
    spec:
      containers:
      - image: project-webpage:v1
        name: nginx
        ports:
        - containerPort: 80

